on:
  repository_dispatch:

concurrency: 
  group: ${{ github.wokflow_ref == 'main.yml' }}
  cancel-in-progress: false

name: PUMA Azure VM Reservation

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Check Working directory
      run: |
        pwd
  
    - name: Install required PowerShell modules
      shell: pwsh
      run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Az.Storage -Scope CurrentUser -Repository PSGallery

    - name: Download CSV
      run: |
        if curl -o /home/runner/work/AzureStuff/AzureStuff/azurevmnames.csv https://villatestsa.blob.core.windows.net/azure-vmname/azurevmnames.csv; then
          echo "CSV download successful."
        else
          echo "CSV download failed."
          exit 1
        fi

    - name: Check CSV Location
      run: |
        find . -type f -name azurevmnames.csv

    - name: Check CSV File Size
      id: check-csv
      run: |
       if [ -s /home/runner/work/AzureStuff/AzureStuff/azurevmnames.csv ]; then
          echo "CSV file is not empty."
        else
          echo "CSV file is empty."
          exit 1
        fi

    - name: Read CSV file content - Before PS
      id: Read-csv
      run: |
        cd /home/runner/work/AzureStuff/AzureStuff && tail azurevmnames.csv
    
    - name: Run PS Script
      shell: pwsh
      run: |
        ./VMNAMEReservation/vmnamereservation.ps1

    - name: Read CSV file content - After PS
      id: ReRead-Csv
      run: |
        cd /home/runner/work/AzureStuff/AzureStuff && tail azurevmnames.csv
