on:
  workflow_dispatch:

name: Virtual Machine name reservation

jobs:
  deploy-script:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download New CSV
      run: |
        if (curl -o csv\azurevmnames.csv https://github.com/VillaDaniele/AzureStuff/blob/main/VMNAMEReservation/csv/azurevmnames.csv;) then
          echo "CSV download successful."
        else
          echo "CSV download failed."
          exit 1
        fi

    - name: Run PS Script
      shell: pwsh
      run: |
        ./VMNAMEReservation/vmnamereservation.ps1
